alias ipn='ipython notebook --browser=google-chrome'
alias book='cd /home/rlabbe/Dropbox/book'
alias filter='cd /home/rlabbe/Dropbox/filterpy/filterpy'
alias db='cd /home/rlabbe/Dropbox'
alias gpom='git push origin master'
alias mp='mousepad'
alias p3='source deactivate'
alias p2='source activate python2'
alias cd~='cd ~'
alias gn='geany'
alias vim='vi'
alias sp='spyder'
alias ga='git add'
alias gaa='git add -A'
alias gcm='git commit -m'
alias gst='git status'
alias open='xdg-open'
